WIP: Rewrite more parts

diff --git a/scripts/memory-usage b/scripts/memory-usage
--- a/scripts/memory-usage
+++ b/scripts/memory-usage
@@ -1,65 +1,71 @@
 #!/usr/bin/env bash
-# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
+# SPDX-FileCopyrightText: 2020 Citadel and contributors
 #
-# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
+# SPDX-License-Identifier: MIT
 
-set -euo pipefail
+#set -euo pipefail
 
 CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
 
-get_container_memory_use () {
-  local container="${1}"
+# Fail if not running as root
+if [[ $EUID -ne 0 ]]; then
+  echo "This script must be run as root" 1>&2
+  exit 1
+fi
 
-  local container_memory=0
-
-  local container_pids=$(docker top "${container}" | tail -n +2 | awk '{print $2}')
-  for pid in $container_pids; do
-    local pid_memory=$(ps u "${pid}" | awk '{print $4}' | grep -v 'MEM')
-    if [[ ! -z "${pid_memory}" ]]; then
-      container_memory=$(awk "BEGIN {print ${container_memory}+${pid_memory}}")
-    fi
-  done
-
-  echo "${container_memory}"
+# Get the memory usage of a docker container by name
+function get_memory_usage() {
+  docker stats --no-stream --format "{{.MemPerc}}" "$1" | sed "s/%//"
 }
 
-get_app_memory_use () {
-  local app="${1}"
-
-  local app_memory=0
-
-  local app_containers=$("${CITADEL_ROOT}/app/app-manager.py" compose "${app}" ps | awk '{print $1}' | grep -v 'Name\|-----')
-  for container in $app_containers; do
-    local container_memory=$(get_container_memory_use "${container}")
-    app_memory=$(awk "BEGIN {print ${app_memory}+${container_memory}}")
-  done
-
-  echo "${app_memory}"
+# Convert a memory usage in MiB to the percentage of the total memory
+# With two decimal places
+function mem_usage_to_percent() {
+  local mem_usage="$1"
+  local total_mem="$(cat /proc/meminfo | grep MemTotal | awk '{printf "%d", $2 / 1024}')"
+  echo "$(awk "BEGIN {printf \"%.1f\", $mem_usage / $total_mem * 100}")"
 }
 
+get_total_used_mem_raw() {
+  free -m | awk 'NR==2 {print $3}'
+}
+
+get_total_used_mem() {
+  echo "$(mem_usage_to_percent "$(get_total_used_mem_raw)")"
+}
+
+# To get the containers of the app, list every container whose name starts with the name of the app
+get_app_containers () {
+  local app_name="$1"
+  docker ps -a --format "{{.Names}}" | grep "$app_name"
+}
+
+# Get the memory usage of the whole system, excluding docker containers
+get_system_memory_usage() {
+  local docker_usage_all="$(docker stats --no-stream --format "{{.MemUsage}}" | awk '{sum+=$1} END {print sum}')"
+  # Now, subtract that from get_total_used_mem_raw, and convert the output to a percentage
+  local total_usage="$(get_total_used_mem_raw)"
+  local system_usage="$(awk "BEGIN {printf \"%.1f\", $total_usage - $docker_usage_all}")"
+  echo "$(mem_usage_to_percent "$system_usage")"
+
+}
 main() {
-  local total_system_memory_usage=$(free | awk 'NR==2{print sprintf("%.1f", $3*100/$2) }')
-  echo "total: ${total_system_memory_usage}%"
-
-  local total_container_memory=0
-
-  # Core services memory use
+  echo "total: $(get_total_used_mem)%"&
   for service in bitcoin lnd electrs tor; do
-    local service_memory=$(get_container_memory_use "${service}")
-    total_container_memory=$(awk "BEGIN {print ${total_container_memory}+${service_memory}}")
-    echo "${service}: ${service_memory}%"
+    echo "${service}: $(get_memory_usage "$service")%" &
   done
-
-  # Installed app memory use
   for app in $("${CITADEL_ROOT}/app/app-manager.py" ls-installed); do
-    local app_memory=$(get_app_memory_use "${app}")
-    total_container_memory=$(awk "BEGIN {print ${total_container_memory}+${app_memory}}")
-    echo "${app}: ${app_memory}%"
+    # For every container of the app, get the mem usage, save it, and at the end, print the total mem usage of the app
+    local mem_usage=0
+    for container in $(get_app_containers "$app"); do
+      # Use awk to add, it supports floating point numbers
+      mem_usage=$(awk "BEGIN {printf \"%.2f\", $mem_usage + $(get_memory_usage "$container")}")
+    done
+    wait
+    echo "${app}: $mem_usage%"
   done
-
-  # Misc system memory use
-  local system_memory=$(awk "function pos(x){return(x<0?0:x)} BEGIN {print pos(${total_system_memory_usage}-${total_container_memory})}")
-  echo "system: ${system_memory}%"
+  echo "system: $(get_system_memory_usage)%"
+  wait
 }
 
-main 2> /dev/null | sort --key 2 --numeric-sort --reverse
+main | sort --key 2 --numeric-sort --reverse
